### ISSUE TITLE
.netcore 2

### ISSUE THREAD

**Issue by tynmas02** [mariuszkerl/AspNetCoreSubdomain#57]
Hello! When I add services.AddSubdomains(); I get an error I can't fix. I have imported using Microsoft.Extensions.DependencyInjection; but it doesn't work. Thank, you.

**Comment by mariuszkerl** [comment]
Unfortunatelly you cannot mix attribute routing with subdomain routing. That's not supported right now. Maybe will be in the future.

**Comment by tynmas02** [comment]
Can it be possible if I remove attribute routing?

**Comment by mariuszkerl** [comment]
Yes that should do the trick.

**Comment by tynmas02** [comment]
Hello Mariusz! I have removed it, but it doesn't seem to work. I will send
you my project. Only check values controller and startup. If you could find
the problem I would appreciate it.
 Multitenant.API.zip
<https://drive.google.com/file/d/1VH4IHAd3zQxl66B4HzLTTy-1YaZ54Vtb/view?usp=drive_web>

**Comment by mariuszkerl** [comment]
Thanks for your project. What you have to do is remove route values from all attributes. So if you have [HttpGet("{id}")] for example you have to change it to [HttpGet] and move routing to startup class using extensions supported by this library
https://github.com/mariuszkerl/AspNetCoreSubdomain/wiki/Reference
check MapRoute extensions which have to have hostnames as a parameter.
Secondly configure your system as done in here for sample project
https://github.com/mariuszkerl/AspNetCoreSubdomain/wiki/Running-samples-project
I can run yours fine after doing all of that.
Also worth mentioning is you have to run VS as an admin if you want to be able to debug subdomains on Windows.

**Comment by tynmas02** [comment]
Hello Mariuz! Thank you for all your help! Could you please send me the
project with your modifications? Thank you very much!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mariuszkerl** [comment]
[Multitenant.API.Modified.zip](https://github.com/mariuszkerl/AspNetCoreSubdomain/files/2502673/Multitenant.API.Modified.zip)

**Comment by tynmas02** [comment]
Hello Mariusz! Thank, you for all your time and help. I would like to ask
you, if there is a way I add routes dynamically. What I mean, is when I
register a new user to be added like: username1.localhost.com, for now I
must assign it's route in startup and host file to do so. Thank, you!

**Comment by mariuszkerl** [comment]
Hello, no problem.
In matter of changing route table dynamically there is already some debate on the internet. This library does not provide anything special about it. 
About hosts file you have to [predefine all subdomains ](https://superuser.com/questions/135595/using-wildcards-in-names-in-windows-hosts-file). But when you will host your software somewhere you should be able to route all subdomains using to i.e. IIS.
