### ISSUE TITLE
Bad Request - Invalid Hostname

### ISSUE THREAD

**Issue by forconz** [mariuszkerl/AspNetCoreSubdomain#58]
![20190103232617](https://user-images.githubusercontent.com/9990289/50645664-10610d00-0faf-11e9-9393-584c73183d8f.png)

**Bad Request - Invalid Hostname
HTTP Error 400. The request hostname is invalid.
How to debug AspNetCoreSubdomain locally? I setup step by step reffer to https://github.com/mariuszkerl/AspNetCoreSubdomain/wiki/Debugging-subdomains-locally**

\AspNetCoreSubdomain-1.1.0\AspNetCoreSubdomain-1.1.0\src\.vs\config
```
      <site name="WebSite1" id="1" serverAutoStart="true">
        <application path="/">
          <virtualDirectory path="/" physicalPath="%IIS_SITES_HOME%\WebSite1" />
        </application>
        <bindings>
          <binding protocol="http" bindingInformation=":8080:localhost" />
        </bindings>
      </site>
      <site name="AspNetCoreSubdomain.Samples" id="2">
        <application path="/" applicationPool="Clr4IntegratedAppPool">
          <virtualDirectory path="/" physicalPath="C:\Users\Tao\Downloads\AspNetCoreSubdomain-1.1.0\AspNetCoreSubdomain-1.1.0\src\AspNetCoreSubdomain.Samples" />
        </application>
        <bindings>
          <binding protocol="http" bindingInformation="*:54575:localhost" />
          <binding protocol="http" bindingInformation="*:54575:mycompany.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain1.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain2.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain3.localhost" />
          <binding protocol="http" bindingInformation="*:54575:home.localhost" />
          <binding protocol="http" bindingInformation="*:54575:test.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomains.page.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain.forms.page.localhost" />
        </bindings>
      </site>

```
C:\Windows\System32\drivers\etc\hosts
# To be able to debug subdomains locally
    127.0.0.1   subdomain1.localhost
    127.0.0.1   subdomain2.localhost
    127.0.0.1   subdomain3.localhost
    127.0.0.1   home.localhost
    127.0.0.1   test.localhost
    127.0.0.1	staticsubdomain1.localhost
    127.0.0.1	staticsubdomain2.localhost
    127.0.0.1	subdomains.page.localhost
    127.0.0.1	subdomain.forms.page.localhost
    127.0.0.1       mycompany.localhost

C:\Users\Tao>ping staticsubdomain1.localhost

正在 Ping staticsubdomain1.localhost [127.0.0.1] 具有 32 字节的数据:
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=64
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=64
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=64
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=64

127.0.0.1 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms

C:\Users\Tao>

**Comment by forconz** [comment]
If I want to browse http://staticsubdomain1.localhost:54575/Home/Action4/testparameter
I open \AspNetCoreSubdomain-1.1.0\src\.vs\config\applicationhost.config by vs code.
```
    <sites>
      <site name="WebSite1" id="1" serverAutoStart="true">
        <application path="/">
          <virtualDirectory path="/" physicalPath="%IIS_SITES_HOME%\WebSite1" />
        </application>
        <bindings>
          <binding protocol="http" bindingInformation=":8080:localhost" />
        </bindings>
      </site>
      <site name="AspNetCoreSubdomain.Samples" id="2">
        <application path="/" applicationPool="Clr4IntegratedAppPool">
          <virtualDirectory path="/" physicalPath="C:\Users\Tao\Downloads\AspNetCoreSubdomain-1.1.0\AspNetCoreSubdomain-1.1.0\src\AspNetCoreSubdomain.Samples" />
        </application>
        <bindings>
          <binding protocol="http" bindingInformation="*:54575:localhost" />
          <binding protocol="http" bindingInformation="*:54575:mycompany.localhost" />
          <binding protocol="http" bindingInformation="*:54575:staticsubdomain1.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain1.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain2.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain3.localhost" />
          <binding protocol="http" bindingInformation="*:54575:home.localhost" />
          <binding protocol="http" bindingInformation="*:54575:test.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomains.page.localhost" />
          <binding protocol="http" bindingInformation="*:54575:subdomain.forms.page.localhost" />
        </bindings>
      </site>
```
Edit <bindings> section and add
`<binding protocol="http" bindingInformation="*:54575:staticsubdomain1.localhost" />`

I close vs code and close VS 2017, and I reopen and run VS 2017 as Administrator
So it is ok.I can able to debug subdomains locally. 

![20190104001425](https://user-images.githubusercontent.com/9990289/50648393-0db5e600-0fb6-11e9-9c30-bccc33d233c7.png)

**Comment by mariuszkerl** [comment]
Yeah! Exactly if you want to run subdomains you have to run cmd/vs code/vs20xx as an admin :) great you solved it yourself. Cheers!

**Comment by wildanmuhlis2** [comment]
Hi,

I've experienced the same. I've tried to run it on VS 2019 community with "Run as Administrator" mode. It shows the front page `http://localhost:54575/` but encountered an error when accessing the subdomains `http://subdomain1.localhost:54575/1` `http://area1.localhost:54575/Test/Action1/1` 

Did something missing in my attempt?

![image](https://user-images.githubusercontent.com/11847279/94220821-05cd7080-ff14-11ea-9588-ec18038c9687.png)

@mariuszk
 @forconz

**Comment by wildanmuhlis2** [comment]
Found the issue.

I incorrectly put the bindings code, it should be inside the relevant project bindings
![image](https://user-images.githubusercontent.com/11847279/94234243-894a8a00-ff33-11ea-8c52-63687bf9d676.png)
