### ISSUE TITLE
We can’t connect to the server at subdomain1.localhost

### ISSUE THREAD

**Issue by amir3164** [mariuszkerl/AspNetCoreSubdomain#59]
iam use core2.2 iam add  services.AddSubdomains(); to strup.cs
when load http://subdomain1.localhost:54575/1 
or http://home.localhost:54575/Action5/2
iam see error 
Hmm. We’re having trouble finding that site.

**Comment by mariuszkerl** [comment]
Hi, thanks for notifing me about the issue.
Did you follow wiki info?
[Debugging subdomains locally](https://github.com/mariuszkerl/AspNetCoreSubdomain/wiki/Debugging-subdomains-locally)

**Comment by amir3164** [comment]
thnaks 
iam add  edit files hosts   # 127.0.0.1   home.localhost 
and . Modify section <bindings> add:  <binding protocol="http" bindingInformation="*:54575:home.localhost" />  
but dont work

**Comment by mariuszkerl** [comment]
If you add # as a prefix it means it's commented out. You have to remove it so it will look like this:
  127.0.0.1   subdomain1.localhost
    127.0.0.1   subdomain2.localhost
    127.0.0.1   subdomain3.localhost
    127.0.0.1   home.localhost
    127.0.0.1   test.localhost
    127.0.0.1	staticsubdomain1.localhost
    127.0.0.1	staticsubdomain2.localhost
    127.0.0.1	subdomains.page.localhost
    127.0.0.1	subdomain.forms.page.localhost

**Comment by mariuszkerl** [comment]
Closed due to inactivity
