### ISSUE TITLE
Exception in the Startup app.UseMVC block

### ISSUE THREAD

**Issue by dnnbuddy** [mariuszkerl/AspNetCoreSubdomain#60]
Hi,

I always encounter the following error message when the web app starts.

System.InvalidOperationException: 'Cannot use 'Microsoft.AspNetCore.Routing.SubDomainRoute' with Endpoint Routing.'

I configured the library in asp.net core 2.2 project. Please help.

Thanks

**Comment by mariuszkerl** [comment]
Hi, sorry that late. 
Could you paste your startup.cs? I configured samples project to netcoreapp2.2 and it seems like it's working fine. There is an issue when using netcoreapp3.0
