### ISSUE TITLE
Support Dotnet core 3 

### ISSUE THREAD

**Issue by nemoxtrastaff** [mariuszkerl/AspNetCoreSubdomain#61]
Since dotnet core 3 there's no UseMvc as they moved to UseEndpoints the MapSubdomainRoute is not compatible , any plan to make  it work with dotnet core 3?

**Comment by mariuszkerl** [comment]
Hi, great you are interested in this project.
Didn't have much time to spare lately for it but yes that should be fixed soon.

**Comment by t-val** [comment]
Would be much appreciated.  I attempted to do it myself using the new DynamicRouteValueTransformer but it breaks my generated links.  I believe I am seeming the same issue as reported [here](https://github.com/dotnet/aspnetcore/issues/16965).  Hopefully someone smarter than me can figure this out so I can get my project up .NET Core 3.

**Comment by hermanocordero** [comment]
I am also interested in using this for a project I have in core 3.1. Any update?

**Comment by mariuszkerl** [comment]
You have to set `services.AddMvc(x => x.EnableEndpointRouting = false);` to use subdomain routing. So it does not work with endpoint routing. Besides that you should be ready to go with v2.0.0 🥳
