### ISSUE TITLE
fetching subdomain value in controller

### ISSUE THREAD

**Issue by usmanchou** [mariuszkerl/AspNetCoreSubdomain#66]

**Comment by mariuszkerl** [comment]
Hello,

what is the issue about fetching subdomain in controller? You can find examples on [main page](https://github.com/mariuszkerl/AspNetCoreSubdomain) as also in [the wiki](https://github.com/mariuszkerl/AspNetCoreSubdomain/wiki/Multitenancy-in-subdomain). There are also many examples how to setup startup [in the samples project](https://github.com/mariuszkerl/AspNetCoreSubdomain/blob/master/src/AspNetCoreSubdomain.Samples/Startup.cs)

**Comment by usmanchou** [comment]
thank you very  much for your response. it worked for me.
