### ISSUE TITLE
Activate SSL on Sub-Domain

### ISSUE THREAD

**Issue by usmanchou** [mariuszkerl/AspNetCoreSubdomain#67]
Hello sir, 
I really admire that you have done really a good job. I have checked your code and its working pretty nicely as it should. 
i am facing an issue after running all the stuff. I am unable to Achieve SSL (https) when i switched to any of sub-domain. when i do it shifts to http from https. 
Is there any way to solve this issue, cz application apis does not support requests unless it does not come from a secure protocol. 
Thanks.

**Comment by mariuszkerl** [comment]
Hi,

I don't think there is any influence in this particular scenario from this lib. If we are talking about local environment for development on IIS for `https` you have to add bindings for it with port same as is done in the [wiki page](https://github.com/mariuszkerl/AspNetCoreSubdomain/wiki/Running-samples-project)
i.e. `<binding protocol="https" bindingInformation="*:PORT:staticsubdomain1.localhost" />` where `PORT` is your https port on local. Also note the protocol above is set to `https`.
 If it's not local dev environment then I would check in your place if your http server and ssl cert are configured for fetching requests for subdomains on your main host.

**Comment by usmanchou** [comment]
hello sir,
Thank you for your kind response. I need https in my production env. kindly let me know if you can help me with that? It will be a great favor. 
Thanks

**Comment by mariuszkerl** [comment]
Hello,

it all depends which environment do you use. 
Here you have some hints how to do it in nginx 
https://www.digitalocean.com/community/questions/how-to-create-subdomain-with-nginx-server-in-the-same-droplet
and here for IIS
https://stackoverflow.com/questions/4069278/how-to-set-up-subdomains-on-iis-7

I'm closing this issue since it's unrelated to the lib itself.
